FROM alpine

MAINTAINER Dylan Meissner "https://github.com/dylanmei/slackp"
RUN apk add --no-cache --update ca-certificates

ADD https://github.com/openfaas/faas/releases/download/0.8.0/fwatchdog /usr/bin
RUN chmod +x /usr/bin/fwatchdog

ADD bin/slackp /bin/slackp

ENV fprocess="slackp"
CMD ["fwatchdog"]
